### ISSUE TITLE
Error in dev version of experiment script

### ISSUE THREAD

**Issue by rdnfn** [rdnfn/bauwerk#27]
* bauwerk version: 0.3.1 - dev version
* Python version: 3.9.12
* Operating System: Debian GNU/Linux 11 (bullseye) (docker)

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

I ran the experiment script with the command config below, and got an error message.

command:
```
/opt/conda/bin/bauwerk-exp -m train_steps_per_task=2500 env_cfg.battery_size=5.0 infeasible_control_penalty=True wandb_project=bauwerk_exp08_benchmark penalty_factor=0.1 env_mode=benchmark add_param_obs=True num_train_tasks=20 benchmark="BuildDistC"
```
Error:
```python
Traceback (most recent call last):
  File "/bauwerk/bauwerk/exp/core.py", line 221, in run
    model.learn(
  File "/opt/conda/lib/python3.9/site-packages/stable_baselines3/sac/sac.py", line 309, in learn
    return super().learn(
  File "/opt/conda/lib/python3.9/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 353, in learn
    callback.on_training_start(locals(), globals())
  File "/opt/conda/lib/python3.9/site-packages/stable_baselines3/common/callbacks.py", line 70, in on_training_start
    self._on_training_start()
  File "/opt/conda/lib/python3.9/site-packages/stable_baselines3/common/callbacks.py", line 194, in _on_training_start
    callback.on_training_start(self.locals, self.globals)
  File "/opt/conda/lib/python3.9/site-packages/stable_baselines3/common/callbacks.py", line 70, in on_training_start
    self._on_training_start()
  File "/opt/conda/lib/python3.9/site-packages/stable_baselines3/common/callbacks.py", line 194, in _on_training_start
    callback.on_training_start(self.locals, self.globals)
  File "/opt/conda/lib/python3.9/site-packages/stable_baselines3/common/callbacks.py", line 70, in on_training_start
    self._on_training_start()
  File "/bauwerk/bauwerk/utils/sb3.py", line 360, in _on_training_start
    self._log_image()
  File "/bauwerk/bauwerk/utils/sb3.py", line 382, in _log_image
    img_data = np.frombuffer(plotter.fig.canvas.tostring_rgb(), dtype=np.uint8)
  File "/opt/conda/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 460, in tostring_rgb
    return self.renderer.tostring_rgb()
AttributeError: 'FigureCanvasAgg' object has no attribute 'renderer'
```

**Comment by rdnfn** [comment]
Fixed by updating the imports to include matplotlib backend change. Fix in dev branch.
